---
title: PhD in Celiac Disease Genetics
subtitle: Journey so far
author: 
  - name: Mohammad Sayeef Alam
    affliation:
      - name: K. G. Jebsen Center for Genetic Epidemiology
        address: NTNU, Trondheim
date: 2023-03-20
date-format: long
format: 
  revealjs:
    chalkboard: true
    logo: ntnu_bredde_eng.png
    theme: serif
    slide-number: c/t
    incremental: true
---

## Some background 

-   I come from small village in India called Antar Dwipa with a population of 20000 close to that of Steinkjer.
-   I have moved around a bit all over India pursing education, having left my home at the age of 16.
-   Finished up my MPhil from IIPS, Mumbai in 2021
-   Worked as Health Economic Consultant at Parexel
-   Always aspired to pursue doctoral studies abroad and finally joined NTNU on 1 April 2022.


## Shifting paradigm in interest

:::: {.columns}

::: {.column width="50%"}

:::{.fragment}
Then

-   Work
-   Cook
-   Eat, Sleep & Repeat

:::

:::

::: {.column width="50%"}

:::{.fragment}

Now 

-   Work
-   Ski, Hike, Swim, Read
-   Islam
-   Cook, Eat, Sleep
-   Relax!

:::

:::

::::

## A PhD on genetics of celiac disease

-   This project peaked my interest while I was working on variable selection methods in high dimensional setting of genetic data for my master’s thesis.
-   Genetic studies in Europe on celiac disease have included diagnosed cases.
-   They primary involved high-risk population viz. diagnosed patients, first or second degree relative and also among pediatric patient cases.

## continued

-   We wish to include even the general population into consideration because we know that between 4 to 7 cases go undiagnosed for each diagnosed case.
-   Hopefully including such an unselected population might reveal some novel associations.
-   Polygenic risk scores to assess the individual genetic load and how it is distributed in the population.
-   We wish to prognose the disease using genetic environmental and changed clinical expressions.

## Tusen takk {background-color="#447099"}